/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CardRegistrationIdRouteImport } from './routes/card.$registrationId'
import { Route as AuthPendingRouteImport } from './routes/auth.pending'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminCampsRouteImport } from './routes/admin.camps'
import { Route as AdminSessionsSessionIdRouteImport } from './routes/admin.sessions.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CardRegistrationIdRoute = CardRegistrationIdRouteImport.update({
  id: '/card/$registrationId',
  path: '/card/$registrationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingRoute = AuthPendingRouteImport.update({
  id: '/auth/pending',
  path: '/auth/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampsRoute = AdminCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsSessionIdRoute = AdminSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/camps': typeof AdminCampsRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/pending': typeof AuthPendingRoute
  '/card/$registrationId': typeof CardRegistrationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/camps': typeof AdminCampsRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/pending': typeof AuthPendingRoute
  '/card/$registrationId': typeof CardRegistrationIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/camps': typeof AdminCampsRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/pending': typeof AuthPendingRoute
  '/card/$registrationId': typeof CardRegistrationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/camps'
    | '/admin/new'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/pending'
    | '/card/$registrationId'
    | '/admin/'
    | '/admin/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/camps'
    | '/admin/new'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/pending'
    | '/card/$registrationId'
    | '/admin'
    | '/admin/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/camps'
    | '/admin/new'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/pending'
    | '/card/$registrationId'
    | '/admin/'
    | '/admin/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthPendingRoute: typeof AuthPendingRoute
  CardRegistrationIdRoute: typeof CardRegistrationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/card/$registrationId': {
      id: '/card/$registrationId'
      path: '/card/$registrationId'
      fullPath: '/card/$registrationId'
      preLoaderRoute: typeof CardRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending': {
      id: '/auth/pending'
      path: '/auth/pending'
      fullPath: '/auth/pending'
      preLoaderRoute: typeof AuthPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/camps': {
      id: '/admin/camps'
      path: '/camps'
      fullPath: '/admin/camps'
      preLoaderRoute: typeof AdminCampsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/$sessionId': {
      id: '/admin/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/admin/sessions/$sessionId'
      preLoaderRoute: typeof AdminSessionsSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCampsRoute: typeof AdminCampsRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSessionsSessionIdRoute: typeof AdminSessionsSessionIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampsRoute: AdminCampsRoute,
  AdminNewRoute: AdminNewRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSessionsSessionIdRoute: AdminSessionsSessionIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthPendingRoute: AuthPendingRoute,
  CardRegistrationIdRoute: CardRegistrationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
