import type { VercelRequest, VercelResponse } from "@vercel/node";
import { createClient } from "@supabase/supabase-js";
import OpenAI from "openai";

// Node.js runtime — no 25s Edge cap; Vercel Pro allows up to 300s
export const config = { maxDuration: 120 };

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") return res.status(405).end();

  const supabaseUrl = process.env.VITE_SUPABASE_URL!;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
  const openaiKey = process.env.OPENAI_API_KEY!;

  if (!supabaseUrl || !serviceKey || !openaiKey) {
    return res.status(500).json({ error: "Server misconfiguration" });
  }

  const {
    registrationId,
    childName,
    gender,
    aspiration,
    subject,
    problem,
    roleModel,
    selfDescription,
  } = req.body ?? {};

  if (!registrationId) return res.status(400).json({ error: "registrationId required" });

  const supabase = createClient(supabaseUrl, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  // Verify registrationId exists + return cached image if already generated (idempotency).
  // Return the stored caption too — it's persisted so the card link / re-fetches stay complete.
  const { data: registration, error: regError } = await supabase
    .from("parent_registrations")
    .select("id, image_url, caption")
    .eq("id", registrationId)
    .single();

  if (regError || !registration) {
    return res.status(404).json({ error: "Registration not found" });
  }

  if (registration.image_url) {
    return res
      .status(200)
      .json({ imageUrl: registration.image_url, caption: registration.caption ?? null });
  }

  const name = childName || "a child";
  const genderWord = gender === "girl" ? "girl" : gender === "boy" ? "boy" : "child";

  const openai = new OpenAI({ apiKey: openaiKey });

  // The image render dominates the wait, so we no longer block it behind a GPT
  // "scene design" call. The scene prompt is built directly from the answers, and
  // the caption is generated by GPT-4o-mini IN PARALLEL with the image — so the
  // total time is ~the image render alone instead of (GPT + image) in series.

  const styleOverride = [
    "Illustration style: soft watercolor painting.",
    "Loose expressive brushstrokes, visible watercolor washes, painterly edges.",
    "Warm muted colour palette — ochres, soft reds, dusty greens, gentle yellows.",
    "Children's picture book illustration quality.",
    "Gentle, warm, slightly dreamy mood.",
    "NOT a photograph. NOT photorealistic. NOT CGI. NOT 3D render. NOT digital art.",
    "No text or writing anywhere in the image. Square composition.",
  ].join(" ");

  const scenePrompt = `A ${genderWord} in India actively working as a ${
    aspiration || "changemaker"
  } RIGHT NOW — actually doing the job, not dreaming or wishing. Show the real setting for that work with specific tools and people around them, and a visual nod to their love of ${
    subject || "learning"
  }. Indian clothing, environment and cultural context. Warm, joyful, hopeful atmosphere.`;

  // Caption generation — focused, caption-only, and resolves to "" on any failure
  // so it can never block or reject the parallel image render.
  const captionPromise: Promise<string> = (async () => {
    try {
      const plan = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content:
              "You write one-line poetic captions for children's dream cards at community events in India. Output only valid JSON.",
          },
          {
            role: "user",
            content: `Write a caption for ${name}'s dream card. They want to become ${
              aspiration || "someone great"
            }, love ${subject || "learning"}, want to fix ${
              problem || "problems in the world"
            }, look up to ${roleModel || "someone inspiring"}, and describe themselves as ${
              selfDescription || "brave"
            }.
One beautiful, poetic sentence under 20 words. Use ${name}. Reference their aspiration and the difference they will make. If it fits naturally, you may nod to who they look up to — but never force it. No clichés.
Respond with JSON only: {"caption": "..."}`,
          },
        ],
        max_tokens: 100,
        response_format: { type: "json_object" },
      });
      const parsed = JSON.parse(plan.choices[0].message.content ?? "{}");
      return (parsed.caption ?? "").replace(/^["']|["']$/g, "");
    } catch (err) {
      console.error("Caption generation error (non-fatal):", err);
      return "";
    }
  })();

  const imagePromise = openai.images.generate({
    model: "gpt-image-2",
    prompt: `${scenePrompt} ${styleOverride}`,
    size: "1024x1024",
    quality: "medium",
    n: 1,
  });

  let caption: string;
  let imageBuffer: Buffer;
  try {
    const [cap, imageResponse] = await Promise.all([captionPromise, imagePromise]);
    caption = cap;
    const b64 = imageResponse.data[0].b64_json!;
    imageBuffer = Buffer.from(b64, "base64");
  } catch (err) {
    console.error("Image generation error:", err);
    return res.status(500).json({ error: "Image generation failed" });
  }

  // Step 3: Upload to Supabase Storage
  let publicUrl: string;
  try {
    const fileName = `${registrationId}.png`;
    const { error: uploadError } = await supabase.storage
      .from("dream-cards")
      .upload(fileName, imageBuffer, { contentType: "image/png", upsert: true });

    if (uploadError) throw uploadError;

    const { data } = supabase.storage.from("dream-cards").getPublicUrl(fileName);
    publicUrl = data.publicUrl;
  } catch (err) {
    console.error("Storage error:", err);
    return res.status(500).json({ error: "Failed to store image" });
  }

  // Step 4: Mark card generated
  await supabase
    .from("parent_registrations")
    .update({ card_generated: true, image_url: publicUrl, caption: caption || null })
    .eq("id", registrationId);

  return res.status(200).json({ imageUrl: publicUrl, caption });
}
